# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170216_0811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='gün'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(verbose_name='bitiş saati'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ders adı'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(verbose_name='başlangıç saati'),
        ),
    ]
