# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20170216_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'derslik', 'verbose_name_plural': 'derslikler'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_time',
            field=models.SmallIntegerField(choices=[(9, '09:00 - 09:45'), (10, '10:00 - 10:45'), (11, '11:00 - 11:45'), (12, '12:00 - 12:45'), (13, '13:00 - 13:45'), (14, '14:00 - 14:45'), (15, '15:00 - 15:45'), (16, '16:00 - 16:45'), (17, '17:00 - 17:45'), (18, '18:00 - 18:45'), (19, '19:00 - 19:45'), (20, '20:00 - 20:45')], default=9, verbose_name='ders saati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=250, verbose_name='derslik adı'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='quota',
            field=models.IntegerField(verbose_name='kontenjan'),
        ),
    ]
