# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170222_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_weekly',
            field=models.SmallIntegerField(choices=[(0, 'Evet'), (1, 'Hayır')], default=0, verbose_name='haftalık olarak tekrarla'),
            preserve_default=False,
        ),
    ]
