# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_lecture_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='color',
        ),
    ]
