# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='course.Student'),
        ),
    ]
